import fetch from 'node-fetch';

const jobs = [
  // Software Engineering (15 jobs)
  {
    title: "Senior Full Stack Developer",
    companyName: "TechVision Solutions",
    location: "San Francisco, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 120000,
    maxSalary: 180000,
    description: "We are seeking a highly skilled Senior Full Stack Developer to join our innovative team. You will be responsible for developing and maintaining web applications using modern technologies including React, Node.js, and cloud platforms.",
    requirements: "• 5+ years of experience in full stack development\n• Proficiency in React, Node.js, TypeScript\n• Experience with AWS or Azure cloud platforms\n• Strong understanding of databases (SQL and NoSQL)\n• Knowledge of microservices architecture\n• Experience with CI/CD pipelines",
    responsibilities: "• Design and develop scalable web applications\n• Collaborate with cross-functional teams\n• Mentor junior developers\n• Participate in code reviews and technical discussions\n• Implement best practices for security and performance",
    skills: ["React", "Node.js", "TypeScript", "AWS", "PostgreSQL", "Docker"],
    benefits: "• Competitive salary and equity package\n• Health, dental, and vision insurance\n• 401(k) with company matching\n• Flexible PTO policy\n• Remote work options\n• Professional development budget"
  },
  {
    title: "DevOps Engineer",
    companyName: "CloudFirst Inc",
    location: "Austin, TX",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 90000,
    maxSalary: 140000,
    description: "Join our DevOps team to build and maintain robust infrastructure that supports our rapidly growing platform. You'll work with cutting-edge technologies and help shape our deployment strategies.",
    requirements: "• 3+ years of DevOps or infrastructure experience\n• Proficiency with Kubernetes and Docker\n• Experience with CI/CD tools (Jenkins, GitLab CI)\n• Knowledge of Infrastructure as Code (Terraform, Ansible)\n• Cloud platform experience (AWS, GCP, Azure)\n• Strong scripting skills (Python, Bash)",
    responsibilities: "• Design and implement automated deployment pipelines\n• Manage containerized applications using Kubernetes\n• Monitor system performance and reliability\n• Implement security best practices\n• Collaborate with development teams on infrastructure needs",
    skills: ["Kubernetes", "Docker", "Terraform", "AWS", "Jenkins", "Python"],
    benefits: "• Remote-first culture\n• Comprehensive health benefits\n• Stock options\n• Learning and development stipend\n• Home office setup allowance"
  },
  {
    title: "Frontend React Developer",
    companyName: "Digital Dynamics",
    location: "New York, NY",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 85000,
    maxSalary: 125000,
    description: "We're looking for a passionate Frontend Developer to create exceptional user experiences. You'll work on modern React applications that serve millions of users worldwide.",
    requirements: "• 3+ years of React development experience\n• Strong proficiency in JavaScript/TypeScript\n• Experience with state management (Redux, Context API)\n• Knowledge of modern CSS frameworks (Tailwind, Styled Components)\n• Understanding of responsive design principles\n• Experience with testing frameworks (Jest, React Testing Library)",
    responsibilities: "• Develop responsive and interactive user interfaces\n• Collaborate with UX/UI designers\n• Optimize applications for performance\n• Write comprehensive tests\n• Participate in agile development processes",
    skills: ["React", "TypeScript", "Redux", "Tailwind CSS", "Jest"],
    benefits: "• Competitive salary\n• Health and wellness benefits\n• Catered lunches\n• Professional development opportunities\n• Flexible working hours"
  },
  {
    title: "Backend Python Developer",
    companyName: "DataFlow Systems",
    location: "Seattle, WA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 110000,
    maxSalary: 160000,
    description: "Join our backend team to build scalable APIs and data processing systems. You'll work with large-scale distributed systems and help architect solutions for complex data challenges.",
    requirements: "• 5+ years of Python development experience\n• Experience with FastAPI or Django\n• Strong database skills (PostgreSQL, MongoDB)\n• Knowledge of distributed systems and microservices\n• Experience with message queues (RabbitMQ, Kafka)\n• Understanding of caching strategies (Redis, Memcached)",
    responsibilities: "• Design and implement RESTful APIs\n• Optimize database queries and performance\n• Build data processing pipelines\n• Ensure system security and scalability\n• Mentor junior developers",
    skills: ["Python", "FastAPI", "PostgreSQL", "Redis", "Kafka", "Docker"],
    benefits: "• Competitive compensation package\n• Comprehensive benefits\n• Equity participation\n• Flexible work arrangements\n• Professional growth opportunities"
  },
  {
    title: "Mobile App Developer",
    companyName: "MobileFirst Studios",
    location: "Los Angeles, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 95000,
    maxSalary: 135000,
    description: "Create innovative mobile applications that delight users. You'll work on both iOS and Android platforms using modern development frameworks and tools.",
    requirements: "• 3+ years of mobile app development experience\n• Proficiency in React Native or Flutter\n• Native iOS (Swift) or Android (Kotlin) experience\n• Understanding of mobile UI/UX principles\n• Experience with app store deployment\n• Knowledge of mobile testing frameworks",
    responsibilities: "• Develop cross-platform mobile applications\n• Optimize app performance and user experience\n• Collaborate with designers and product managers\n• Implement push notifications and analytics\n• Maintain code quality and documentation",
    skills: ["React Native", "Swift", "Kotlin", "Flutter", "Firebase"],
    benefits: "• Competitive salary and bonuses\n• Health insurance and wellness programs\n• Creative work environment\n• Latest tech equipment\n• Team building activities"
  },
  {
    title: "QA Engineer",
    companyName: "QualityFirst Testing",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 75000,
    maxSalary: 100000,
    description: "Ensure software quality through comprehensive testing strategies. You'll design test plans, execute test cases, and work with development teams to resolve issues.",
    requirements: "• 3+ years of QA testing experience\n• Experience with manual and automated testing\n• Knowledge of testing frameworks (Selenium, Cypress)\n• Understanding of API testing and tools (Postman)\n• Experience with bug tracking systems (Jira)\n• Knowledge of agile testing methodologies",
    responsibilities: "• Create comprehensive test plans and test cases\n• Execute manual and automated tests\n• Identify, document, and track software defects\n• Collaborate with developers on bug resolution\n• Participate in agile ceremonies and release planning",
    skills: ["QA Testing", "Test Automation", "Selenium", "API Testing", "Jira"],
    benefits: "• Remote work flexibility\n• Competitive salary\n• Health insurance coverage\n• Professional development budget\n• Quality tools and resources"
  },
  {
    title: "Cybersecurity Analyst",
    companyName: "SecureShield Technologies",
    location: "Washington, DC",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 85000,
    maxSalary: 115000,
    description: "Protect organizational assets through proactive security monitoring and incident response. You'll implement security measures and investigate potential threats.",
    requirements: "• 3+ years of cybersecurity experience\n• Knowledge of security frameworks (NIST, ISO 27001)\n• Experience with SIEM tools and log analysis\n• Understanding of network security and protocols\n• Security certifications (Security+, CISSP) preferred\n• Incident response and forensics experience",
    responsibilities: "• Monitor security events and investigate incidents\n• Implement and maintain security controls\n• Conduct vulnerability assessments and penetration testing\n• Develop security policies and procedures\n• Provide security training and awareness",
    skills: ["Cybersecurity", "SIEM", "Incident Response", "Vulnerability Assessment"],
    benefits: "• Government contract opportunities\n• Security clearance support\n• Comprehensive benefits\n• Certification reimbursement\n• Career advancement in security"
  },
  {
    title: "Database Administrator",
    companyName: "DataCore Systems",
    location: "Phoenix, AZ",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 90000,
    maxSalary: 125000,
    description: "Manage and optimize database systems to ensure high performance and availability. You'll work with various database technologies and support mission-critical applications.",
    requirements: "• 5+ years of database administration experience\n• Expertise in SQL Server, Oracle, or PostgreSQL\n• Experience with database performance tuning\n• Knowledge of backup and recovery procedures\n• Understanding of database security best practices\n• Cloud database experience (AWS RDS, Azure SQL) preferred",
    responsibilities: "• Install, configure, and maintain database systems\n• Monitor database performance and optimize queries\n• Implement backup and recovery strategies\n• Ensure database security and compliance\n• Support application development teams",
    skills: ["Database Administration", "SQL Server", "PostgreSQL", "Performance Tuning"],
    benefits: "• Competitive salary and bonuses\n• Health and wellness benefits\n• On-call compensation\n• Professional certification support\n• Technical training opportunities"
  },
  {
    title: "Cloud Solutions Architect",
    companyName: "CloudFirst Architecture",
    location: "Seattle, WA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 130000,
    maxSalary: 180000,
    description: "Design and implement cloud-based solutions that meet business requirements. You'll work with clients to architect scalable and secure cloud infrastructures.",
    requirements: "• 6+ years of cloud architecture experience\n• Expertise in AWS, Azure, or Google Cloud Platform\n• Experience with containerization (Docker, Kubernetes)\n• Knowledge of infrastructure as code (Terraform, CloudFormation)\n• Understanding of microservices architecture\n• Cloud certifications (AWS Solutions Architect, Azure Architect)",
    responsibilities: "• Design cloud architecture solutions for clients\n• Lead cloud migration and transformation projects\n• Implement security and compliance best practices\n• Optimize cloud costs and performance\n• Mentor junior architects and engineers",
    skills: ["Cloud Architecture", "AWS", "Kubernetes", "Terraform", "Microservices"],
    benefits: "• Senior-level compensation\n• Equity participation\n• Comprehensive benefits\n• Cloud certification reimbursement\n• Technical leadership opportunities"
  },
  {
    title: "Software Engineering Manager",
    companyName: "Tech Leadership Corp",
    location: "San Francisco, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 150000,
    maxSalary: 220000,
    description: "Lead a team of talented engineers to deliver high-quality software products. You'll balance technical leadership with people management in a fast-paced environment.",
    requirements: "• 7+ years of software engineering experience\n• 3+ years of team leadership experience\n• Strong technical background in modern web technologies\n• Experience with agile development methodologies\n• Excellent communication and mentoring skills\n• Track record of delivering successful products",
    responsibilities: "• Lead and mentor a team of software engineers\n• Define technical roadmap and architecture decisions\n• Collaborate with product and design teams\n• Conduct performance reviews and career development\n• Ensure code quality and best practices",
    skills: ["Engineering Management", "Team Leadership", "Architecture", "Agile", "Mentoring"],
    benefits: "• Executive-level compensation\n• Equity package\n• Leadership development programs\n• Flexible work arrangements\n• Innovation budget"
  },
  {
    title: "Junior Software Developer",
    companyName: "CodeCraft Startup",
    location: "Austin, TX",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "entry",
    minSalary: 65000,
    maxSalary: 85000,
    description: "Join our growing startup as a junior developer and learn from experienced engineers. You'll work on exciting projects and have opportunities to grow your skills rapidly.",
    requirements: "• Bachelor's degree in Computer Science or related field\n• 0-2 years of professional development experience\n• Knowledge of at least one programming language (JavaScript, Python, Java)\n• Understanding of basic web development concepts\n• Eagerness to learn and grow\n• Strong problem-solving skills",
    responsibilities: "• Write clean, maintainable code under guidance\n• Participate in code reviews and team meetings\n• Learn new technologies and frameworks\n• Contribute to feature development and bug fixes\n• Collaborate with senior developers on projects",
    skills: ["JavaScript", "Python", "HTML/CSS", "Git", "Learning"],
    benefits: "• Mentorship program\n• Learning and development budget\n• Health insurance\n• Startup equity\n• Casual work environment"
  },
  {
    title: "Site Reliability Engineer",
    companyName: "ScaleOps Infrastructure",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 100000,
    maxSalary: 140000,
    description: "Ensure the reliability and performance of our production systems. You'll work on automation, monitoring, and incident response to maintain high availability.",
    requirements: "• 4+ years of SRE or operations experience\n• Strong programming skills (Python, Go, or similar)\n• Experience with monitoring and alerting tools\n• Knowledge of containerization and orchestration\n• Understanding of distributed systems\n• Experience with incident management",
    responsibilities: "• Monitor system health and performance\n• Automate operational tasks and processes\n• Respond to and resolve production incidents\n• Improve system reliability and scalability\n• Collaborate with development teams on best practices",
    skills: ["SRE", "Python", "Monitoring", "Automation", "Incident Response"],
    benefits: "• Remote-first culture\n• On-call compensation\n• Professional development\n• Health benefits\n• Stock options"
  },
  {
    title: "AI/ML Engineer",
    companyName: "AI Innovations Lab",
    location: "San Francisco, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 115000,
    maxSalary: 165000,
    description: "Develop and deploy machine learning models that power our AI-driven products. You'll work with large datasets and cutting-edge ML technologies.",
    requirements: "• 3+ years of ML engineering experience\n• Strong background in Python and ML frameworks (TensorFlow, PyTorch)\n• Experience with data preprocessing and feature engineering\n• Knowledge of cloud ML platforms (AWS SageMaker, GCP ML)\n• Understanding of MLOps and model deployment\n• Experience with deep learning and neural networks",
    responsibilities: "• Design and implement ML models and algorithms\n• Build data pipelines for model training\n• Deploy models to production environments\n• Monitor model performance and accuracy\n• Collaborate with data scientists and engineers",
    skills: ["Machine Learning", "Python", "TensorFlow", "MLOps", "Data Engineering"],
    benefits: "• Cutting-edge AI projects\n• Research conference attendance\n• Comprehensive benefits\n• GPU resources for experimentation\n• Collaborative research environment"
  },
  {
    title: "Data Engineer",
    companyName: "BigData Solutions",
    location: "Seattle, WA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 95000,
    maxSalary: 130000,
    description: "Build and maintain data infrastructure that enables analytics and machine learning. You'll work with big data technologies and design scalable data pipelines.",
    requirements: "• 3+ years of data engineering experience\n• Proficiency in SQL and Python\n• Experience with big data technologies (Spark, Hadoop, Kafka)\n• Knowledge of cloud data services (AWS, GCP, Azure)\n• Understanding of data warehousing concepts\n• Experience with ETL/ELT processes",
    responsibilities: "• Design and build data pipelines and ETL processes\n• Optimize data storage and retrieval systems\n• Ensure data quality and reliability\n• Collaborate with data scientists and analysts\n• Implement data governance and security measures",
    skills: ["Data Engineering", "Python", "SQL", "Spark", "ETL"],
    benefits: "• Data technology exposure\n• Professional development\n• Health and dental coverage\n• Flexible schedule\n• Remote work options"
  },
  {
    title: "Platform Engineer",
    companyName: "Infrastructure Plus",
    location: "Denver, CO",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 105000,
    maxSalary: 145000,
    description: "Build and maintain developer platforms that enable efficient software delivery. You'll work on internal tools and infrastructure automation.",
    requirements: "• 5+ years of platform or infrastructure experience\n• Strong knowledge of Kubernetes and container technologies\n• Experience with Infrastructure as Code (Terraform, Pulumi)\n• Programming skills in Go, Python, or similar\n• Understanding of CI/CD and GitOps\n• Experience with service mesh and observability",
    responsibilities: "• Design and implement developer platform tools\n• Automate infrastructure provisioning and management\n• Build self-service capabilities for development teams\n• Ensure platform reliability and performance\n• Provide technical guidance and support",
    skills: ["Platform Engineering", "Kubernetes", "Terraform", "Go", "GitOps"],
    benefits: "• Technical leadership opportunities\n• Conference attendance\n• Health benefits\n• Stock options\n• Learning budget"
  },

  // Marketing (10 jobs)
  {
    title: "Digital Marketing Manager",
    companyName: "GrowthLab Marketing",
    location: "Chicago, IL",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 70000,
    maxSalary: 95000,
    description: "Lead our digital marketing initiatives and drive growth through innovative campaigns. You'll manage multiple channels and work with cross-functional teams to achieve business objectives.",
    requirements: "• 4+ years of digital marketing experience\n• Proficiency in Google Analytics, Google Ads\n• Experience with social media advertising (Facebook, LinkedIn, Twitter)\n• Knowledge of SEO/SEM best practices\n• Content marketing and email marketing experience\n• Data analysis and reporting skills",
    responsibilities: "• Develop and execute digital marketing strategies\n• Manage PPC campaigns and budgets\n• Create content for various marketing channels\n• Analyze campaign performance and ROI\n• Collaborate with sales and product teams",
    skills: ["Google Analytics", "Google Ads", "SEO", "Content Marketing", "Social Media"],
    benefits: "• Performance-based bonuses\n• Health and dental insurance\n• Professional development budget\n• Flexible work schedule\n• Marketing conference attendance"
  },
  {
    title: "Content Marketing Specialist",
    companyName: "ContentCraft Agency",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 55000,
    maxSalary: 75000,
    description: "Create compelling content that drives engagement and conversions. You'll work on blog posts, social media content, email campaigns, and marketing materials for diverse clients.",
    requirements: "• 3+ years of content marketing experience\n• Excellent writing and editing skills\n• Experience with content management systems\n• Knowledge of SEO writing techniques\n• Social media management experience\n• Basic graphic design skills (Canva, Adobe Creative Suite)",
    responsibilities: "• Create blog posts, articles, and web content\n• Develop social media content calendars\n• Write email marketing campaigns\n• Optimize content for SEO\n• Collaborate with design and marketing teams",
    skills: ["Content Writing", "SEO", "WordPress", "Social Media", "Email Marketing"],
    benefits: "• Fully remote position\n• Flexible working hours\n• Health insurance coverage\n• Professional development opportunities\n• Creative freedom and autonomy"
  },
  {
    title: "Social Media Manager",
    companyName: "Brand Builders Co",
    location: "Miami, FL",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 50000,
    maxSalary: 70000,
    description: "Manage social media presence for multiple brands and build engaged communities. You'll create content, run campaigns, and analyze performance across all major platforms.",
    requirements: "• 3+ years of social media management experience\n• Proficiency in social media scheduling tools (Hootsuite, Buffer)\n• Experience with paid social advertising\n• Strong visual content creation skills\n• Knowledge of social media analytics\n• Understanding of brand voice and messaging",
    responsibilities: "• Develop social media strategies and content calendars\n• Create engaging visual and written content\n• Manage community interactions and responses\n• Run paid social media campaigns\n• Track and report on social media metrics",
    skills: ["Social Media Marketing", "Content Creation", "Paid Advertising", "Analytics"],
    benefits: "• Vibrant office culture\n• Health and wellness benefits\n• Creative workspace\n• Team lunches and events\n• Growth opportunities"
  },
  {
    title: "SEO Specialist",
    companyName: "SearchPro Digital",
    location: "Denver, CO",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 60000,
    maxSalary: 85000,
    description: "Drive organic traffic growth through strategic SEO initiatives. You'll work on technical SEO, content optimization, and link building strategies for diverse clients.",
    requirements: "• 3+ years of SEO experience\n• Proficiency in SEO tools (SEMrush, Ahrefs, Moz)\n• Technical SEO knowledge (site speed, crawling, indexing)\n• Experience with Google Search Console and Analytics\n• Understanding of keyword research and competitor analysis\n• Basic HTML/CSS knowledge",
    responsibilities: "• Conduct SEO audits and develop optimization strategies\n• Perform keyword research and competitor analysis\n• Optimize website content and meta tags\n• Build high-quality backlinks\n• Monitor and report on SEO performance",
    skills: ["SEO", "Google Analytics", "SEMrush", "Technical SEO", "Link Building"],
    benefits: "• Remote work flexibility\n• Performance bonuses\n• Health insurance\n• Professional certification support\n• Career advancement opportunities"
  },
  {
    title: "Email Marketing Specialist",
    companyName: "EmailExpert Solutions",
    location: "Boston, MA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 55000,
    maxSalary: 75000,
    description: "Design and execute email marketing campaigns that drive engagement and revenue. You'll work with automation tools and analyze campaign performance to optimize results.",
    requirements: "• 3+ years of email marketing experience\n• Proficiency in email platforms (Mailchimp, Klaviyo, SendGrid)\n• Experience with email automation and segmentation\n• HTML/CSS skills for email templates\n• A/B testing and analytics experience\n• Understanding of deliverability best practices",
    responsibilities: "• Create and manage email marketing campaigns\n• Develop automated email sequences\n• Design responsive email templates\n• Segment audiences for targeted messaging\n• Analyze campaign performance and optimize results",
    skills: ["Email Marketing", "Marketing Automation", "HTML/CSS", "Analytics"],
    benefits: "• Competitive salary\n• Comprehensive benefits package\n• Flexible work arrangements\n• Professional development budget\n• Collaborative team environment"
  },
  {
    title: "Growth Marketing Manager",
    companyName: "ScaleUp Growth",
    location: "San Francisco, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 95000,
    maxSalary: 130000,
    description: "Drive user acquisition and retention through data-driven growth strategies. You'll experiment with various channels and optimize the entire customer funnel.",
    requirements: "• 4+ years of growth marketing experience\n• Strong analytical skills and data-driven mindset\n• Experience with A/B testing and experimentation\n• Knowledge of growth hacking techniques\n• Proficiency in analytics tools (Google Analytics, Mixpanel)\n• Experience with paid acquisition channels",
    responsibilities: "• Develop and execute growth strategies\n• Run A/B tests and analyze results\n• Optimize conversion funnels\n• Manage paid acquisition campaigns\n• Collaborate with product and engineering teams",
    skills: ["Growth Marketing", "A/B Testing", "Analytics", "Paid Acquisition", "Conversion Optimization"],
    benefits: "• Equity package\n• Performance bonuses\n• Learning and development budget\n• Remote work options\n• Innovation time"
  },
  {
    title: "Brand Marketing Manager",
    companyName: "BrandCraft Agency",
    location: "Los Angeles, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 75000,
    maxSalary: 100000,
    description: "Build and maintain brand identity across all marketing channels. You'll develop brand strategies and ensure consistent messaging that resonates with target audiences.",
    requirements: "• 4+ years of brand marketing experience\n• Strong creative and strategic thinking\n• Experience with brand positioning and messaging\n• Knowledge of design principles and brand guidelines\n• Experience with influencer and partnership marketing\n• Bachelor's degree in Marketing or Communications",
    responsibilities: "• Develop brand strategy and positioning\n• Create brand guidelines and messaging frameworks\n• Manage brand partnerships and collaborations\n• Oversee creative campaigns and content\n• Monitor brand perception and awareness",
    skills: ["Brand Marketing", "Brand Strategy", "Creative Direction", "Partnership Marketing"],
    benefits: "• Creative work environment\n• Health and wellness benefits\n• Brand conference attendance\n• Professional development opportunities\n• Collaborative team culture"
  },
  {
    title: "Marketing Analytics Manager",
    companyName: "DataDriven Marketing",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 85000,
    maxSalary: 115000,
    description: "Lead marketing analytics initiatives to measure and optimize campaign performance. You'll work with large datasets to provide insights that drive marketing strategy.",
    requirements: "• 5+ years of marketing analytics experience\n• Advanced SQL and data analysis skills\n• Experience with analytics tools (Google Analytics, Adobe Analytics)\n• Knowledge of statistical analysis and modeling\n• Proficiency in data visualization tools (Tableau, Looker)\n• Understanding of marketing attribution models",
    responsibilities: "• Analyze marketing campaign performance across channels\n• Build dashboards and reports for marketing teams\n• Develop attribution models and measurement frameworks\n• Provide insights and recommendations for optimization\n• Collaborate with data science and engineering teams",
    skills: ["Marketing Analytics", "SQL", "Tableau", "Statistical Analysis", "Attribution Modeling"],
    benefits: "• Remote work flexibility\n• Data tools and resources\n• Professional development budget\n• Performance bonuses\n• Analytics conference attendance"
  },
  {
    title: "Product Marketing Manager",
    companyName: "ProductLaunch Inc",
    location: "Seattle, WA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 80000,
    maxSalary: 110000,
    description: "Drive product marketing strategy and go-to-market execution. You'll work closely with product and sales teams to position products effectively in the market.",
    requirements: "• 4+ years of product marketing experience\n• Strong understanding of product positioning and messaging\n• Experience with competitive analysis and market research\n• Knowledge of sales enablement and training\n• Excellent presentation and communication skills\n• Background in B2B or SaaS marketing preferred",
    responsibilities: "• Develop product positioning and messaging\n• Create go-to-market strategies for new products\n• Conduct competitive analysis and market research\n• Enable sales teams with training and materials\n• Collaborate with product management on roadmap",
    skills: ["Product Marketing", "Go-to-Market", "Competitive Analysis", "Sales Enablement"],
    benefits: "• Product launch opportunities\n• Cross-functional collaboration\n• Health benefits\n• Stock options\n• Professional growth"
  },
  {
    title: "Marketing Operations Specialist",
    companyName: "MarTech Solutions",
    location: "Austin, TX",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 65000,
    maxSalary: 90000,
    description: "Optimize marketing processes and technology stack to drive efficiency and performance. You'll work with marketing automation platforms and data systems.",
    requirements: "• 3+ years of marketing operations experience\n• Experience with marketing automation platforms (HubSpot, Marketo, Pardot)\n• Strong analytical and problem-solving skills\n• Knowledge of CRM systems and data management\n• Understanding of lead scoring and nurturing\n• Experience with reporting and dashboard creation",
    responsibilities: "• Manage marketing automation and lead nurturing\n• Optimize marketing processes and workflows\n• Maintain data quality and hygiene\n• Create reports and dashboards for marketing teams\n• Support campaign execution and tracking",
    skills: ["Marketing Operations", "Marketing Automation", "HubSpot", "Data Management", "Process Optimization"],
    benefits: "• MarTech exposure\n• Process improvement opportunities\n• Health insurance\n• Professional development\n• Career advancement"
  },

  // Sales (10 jobs)
  {
    title: "Enterprise Sales Executive",
    companyName: "SalesPro Enterprise",
    location: "San Francisco, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 80000,
    maxSalary: 120000,
    description: "Drive enterprise sales for our B2B software solutions. You'll work with Fortune 500 companies to understand their needs and provide technology solutions that transform their business.",
    requirements: "• 5+ years of enterprise B2B sales experience\n• Track record of closing deals $100K+\n• Experience with CRM systems (Salesforce, HubSpot)\n• Strong presentation and negotiation skills\n• Technology or SaaS sales background preferred\n• Bachelor's degree in Business or related field",
    responsibilities: "• Identify and pursue enterprise sales opportunities\n• Conduct product demonstrations and presentations\n• Negotiate contracts and close deals\n• Build relationships with C-level executives\n• Collaborate with technical teams for solution design",
    skills: ["Enterprise Sales", "B2B Sales", "Salesforce", "Negotiation", "Presentations"],
    benefits: "• Base salary plus uncapped commission\n• Comprehensive benefits package\n• Sales incentive trips\n• Professional development programs\n• Stock options"
  },
  {
    title: "Inside Sales Representative",
    companyName: "TechSales Solutions",
    location: "Austin, TX",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "entry",
    minSalary: 45000,
    maxSalary: 65000,
    description: "Join our inside sales team to help businesses discover our software solutions. You'll work with inbound leads and conduct outbound prospecting to build a strong sales pipeline.",
    requirements: "• 1-2 years of sales experience (entry level considered)\n• Excellent communication and phone skills\n• Experience with CRM systems preferred\n• Goal-oriented and self-motivated\n• Bachelor's degree preferred\n• Technology aptitude and interest in SaaS",
    responsibilities: "• Follow up on inbound leads and qualify prospects\n• Conduct outbound prospecting calls and emails\n• Schedule demos for field sales team\n• Maintain accurate records in CRM\n• Achieve monthly and quarterly sales targets",
    skills: ["Inside Sales", "Lead Generation", "CRM", "Phone Sales", "Prospecting"],
    benefits: "• Base salary plus commission\n• Health and dental insurance\n• Career growth opportunities\n• Sales training programs\n• Team building activities"
  },
  {
    title: "Account Manager",
    companyName: "ClientFirst Services",
    location: "Chicago, IL",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 60000,
    maxSalary: 80000,
    description: "Manage and grow relationships with existing clients to ensure satisfaction and identify expansion opportunities. You'll serve as the primary point of contact for key accounts.",
    requirements: "• 3+ years of account management experience\n• Strong relationship building skills\n• Experience with client retention and upselling\n• Proficiency in CRM and account management tools\n• Excellent problem-solving abilities\n• Bachelor's degree in Business or related field",
    responsibilities: "• Manage portfolio of existing client accounts\n• Identify upselling and cross-selling opportunities\n• Resolve client issues and ensure satisfaction\n• Conduct regular business reviews with clients\n• Collaborate with internal teams to deliver solutions",
    skills: ["Account Management", "Client Relations", "Upselling", "Problem Solving"],
    benefits: "• Competitive base salary and bonuses\n• Comprehensive benefits\n• Professional development opportunities\n• Flexible work schedule\n• Client entertainment budget"
  },
  {
    title: "Business Development Representative",
    companyName: "GrowthEngine Corp",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "entry",
    minSalary: 50000,
    maxSalary: 70000,
    description: "Generate new business opportunities through strategic outreach and relationship building. You'll identify potential clients and set the foundation for future sales success.",
    requirements: "• 1-3 years of sales or business development experience\n• Strong prospecting and lead generation skills\n• Experience with sales tools (LinkedIn Sales Navigator, Outreach)\n• Excellent written and verbal communication\n• Self-motivated and results-driven\n• Bachelor's degree preferred",
    responsibilities: "• Research and identify potential business opportunities\n• Conduct outbound prospecting via phone, email, and social media\n• Qualify leads and schedule meetings for sales team\n• Maintain prospect database and track activities\n• Collaborate with marketing on lead generation campaigns",
    skills: ["Business Development", "Lead Generation", "Prospecting", "LinkedIn Sales Navigator"],
    benefits: "• Remote work flexibility\n• Base salary plus performance bonuses\n• Health insurance coverage\n• Professional development budget\n• Career advancement opportunities"
  },
  {
    title: "Sales Operations Analyst",
    companyName: "SalesOps Pro",
    location: "Seattle, WA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 70000,
    maxSalary: 95000,
    description: "Support sales team efficiency through data analysis, process optimization, and sales technology management. You'll provide insights that drive sales performance and growth.",
    requirements: "• 3+ years of sales operations or analytics experience\n• Strong analytical and data visualization skills\n• Proficiency in Salesforce and sales analytics tools\n• Excel/Google Sheets expertise\n• Experience with sales forecasting and reporting\n• SQL knowledge preferred",
    responsibilities: "• Analyze sales performance and provide insights\n• Manage sales technology stack and integrations\n• Create dashboards and reports for sales leadership\n• Optimize sales processes and workflows\n• Support sales forecasting and planning",
    skills: ["Sales Operations", "Salesforce", "Data Analysis", "Excel", "SQL"],
    benefits: "• Competitive salary and bonuses\n• Comprehensive benefits package\n• Professional development opportunities\n• Flexible work arrangements\n• Stock options"
  },
  {
    title: "Channel Sales Manager",
    companyName: "PartnerNetwork Solutions",
    location: "Dallas, TX",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 90000,
    maxSalary: 120000,
    description: "Develop and manage strategic channel partnerships to drive revenue growth. You'll work with resellers, distributors, and technology partners to expand market reach.",
    requirements: "• 5+ years of channel sales or partnership experience\n• Experience building and managing partner relationships\n• Strong negotiation and contract management skills\n• Knowledge of channel marketing and enablement\n• Experience with partner portals and CRM systems\n• Bachelor's degree in Business or related field",
    responsibilities: "• Recruit and onboard new channel partners\n• Develop partner enablement programs and training\n• Manage partner performance and relationships\n• Create channel marketing programs\n• Negotiate partnership agreements and contracts",
    skills: ["Channel Sales", "Partnership Management", "Negotiation", "Partner Enablement"],
    benefits: "• Base salary plus commission\n• Travel opportunities\n• Partnership conference attendance\n• Professional development budget\n• Leadership opportunities"
  },
  {
    title: "Sales Development Representative",
    companyName: "LeadGen Dynamics",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "entry",
    minSalary: 45000,
    maxSalary: 65000,
    description: "Generate qualified leads for the sales team through outbound prospecting and inbound lead qualification. You'll be the first point of contact for potential customers.",
    requirements: "• 0-2 years of sales or SDR experience\n• Strong communication and phone skills\n• Experience with sales tools and CRM systems\n• Resilient and goal-oriented mindset\n• Interest in technology and B2B sales\n• Bachelor's degree preferred",
    responsibilities: "• Conduct outbound prospecting calls and emails\n• Qualify inbound leads and marketing inquiries\n• Schedule qualified meetings for account executives\n• Research prospects and personalize outreach\n• Meet monthly and quarterly activity and conversion targets",
    skills: ["Lead Generation", "Prospecting", "Sales Development", "CRM", "Communication"],
    benefits: "• Accelerated career path to AE role\n• Comprehensive sales training\n• Base salary plus bonuses\n• Remote work setup\n• Health insurance"
  },
  {
    title: "Regional Sales Manager",
    companyName: "Territory Sales Corp",
    location: "Atlanta, GA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 85000,
    maxSalary: 115000,
    description: "Lead sales efforts across assigned geographic region and manage a team of sales representatives. You'll drive revenue growth and develop regional market strategies.",
    requirements: "• 6+ years of B2B sales experience\n• 2+ years of sales management experience\n• Proven track record of exceeding sales targets\n• Experience with territory planning and management\n• Strong leadership and coaching skills\n• Travel availability within assigned region",
    responsibilities: "• Manage and coach regional sales team\n• Develop and execute regional sales strategies\n• Build relationships with key regional accounts\n• Analyze market trends and competitive landscape\n• Forecast sales and manage regional pipeline",
    skills: ["Sales Management", "Territory Management", "Team Leadership", "Forecasting"],
    benefits: "• Management-level compensation\n• Car allowance and travel reimbursement\n• Leadership development programs\n• Performance bonuses\n• Stock options"
  },
  {
    title: "Customer Success Manager",
    companyName: "CustomerFirst Solutions",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 65000,
    maxSalary: 85000,
    description: "Ensure customer satisfaction and drive product adoption. You'll work closely with clients to help them achieve their goals and maximize value from our solutions.",
    requirements: "• 3+ years of customer success or account management experience\n• Strong relationship building and communication skills\n• Experience with CRM and customer success platforms\n• SaaS or technology industry experience preferred\n• Problem-solving and analytical skills\n• Bachelor's degree preferred",
    responsibilities: "• Onboard new customers and ensure successful adoption\n• Build strong relationships with key stakeholders\n• Identify expansion opportunities and reduce churn\n• Provide product training and support\n• Gather customer feedback and collaborate with product teams",
    skills: ["Customer Success", "Account Management", "Relationship Building", "SaaS"],
    benefits: "• Remote work flexibility\n• Competitive salary and bonuses\n• Health insurance coverage\n• Customer success training\n• Career growth opportunities"
  },
  {
    title: "Sales Engineer",
    companyName: "TechSolution Sales",
    location: "San Jose, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 95000,
    maxSalary: 130000,
    description: "Combine technical expertise with sales skills to support complex B2B sales cycles. You'll conduct technical demos and work with engineering teams on solution design.",
    requirements: "• 4+ years of technical or engineering background\n• 2+ years of sales or customer-facing experience\n• Strong presentation and communication skills\n• Experience with technical product demonstrations\n• Understanding of enterprise software solutions\n• Engineering or technical degree preferred",
    responsibilities: "• Conduct technical product demonstrations\n• Support sales team with technical expertise\n• Collaborate on solution design and proposals\n• Address technical questions and objections\n• Build relationships with technical stakeholders",
    skills: ["Sales Engineering", "Technical Sales", "Product Demos", "Solution Design"],
    benefits: "• Technical and sales skill development\n• Competitive salary and commission\n• Conference and training attendance\n• Health benefits\n• Stock options"
  },

  // HR (10 jobs)
  {
    title: "HR Business Partner",
    companyName: "PeopleFirst Solutions",
    location: "New York, NY",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 85000,
    maxSalary: 115000,
    description: "Partner with business leaders to drive HR strategy and support organizational goals. You'll provide strategic HR guidance and help build a positive workplace culture.",
    requirements: "• 5+ years of HR business partner experience\n• Strong knowledge of employment law and HR best practices\n• Experience with performance management and employee relations\n• SHRM-CP or PHR certification preferred\n• Bachelor's degree in HR or related field\n• Change management experience",
    responsibilities: "• Partner with leadership on HR strategy and initiatives\n• Provide guidance on employee relations issues\n• Support performance management processes\n• Lead organizational change initiatives\n• Develop and implement HR policies and procedures",
    skills: ["HR Strategy", "Employee Relations", "Performance Management", "Change Management"],
    benefits: "• Competitive salary and annual bonus\n• Comprehensive benefits package\n• Professional development budget\n• Flexible work arrangements\n• Wellness programs"
  },
  {
    title: "Talent Acquisition Specialist",
    companyName: "TalentHub Recruiting",
    location: "San Diego, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 60000,
    maxSalary: 80000,
    description: "Lead end-to-end recruitment efforts to attract top talent across various roles. You'll work with hiring managers to understand needs and build strong candidate pipelines.",
    requirements: "• 3+ years of recruiting or talent acquisition experience\n• Experience with applicant tracking systems (ATS)\n• Strong sourcing skills using LinkedIn and other platforms\n• Knowledge of employment law and hiring best practices\n• Excellent interviewing and assessment skills\n• Bachelor's degree preferred",
    responsibilities: "• Partner with hiring managers to understand role requirements\n• Source candidates through various channels\n• Conduct initial candidate screenings and interviews\n• Manage candidate experience throughout hiring process\n• Build and maintain talent pipelines",
    skills: ["Recruiting", "Talent Sourcing", "ATS", "Interviewing", "LinkedIn Recruiting"],
    benefits: "• Competitive salary with recruiting bonuses\n• Health and dental insurance\n• Professional development opportunities\n• Flexible work schedule\n• Recruiting conference attendance"
  },
  {
    title: "HR Generalist",
    companyName: "CompleteCare HR",
    location: "Phoenix, AZ",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 55000,
    maxSalary: 75000,
    description: "Support all aspects of HR operations including employee relations, benefits administration, and policy implementation. You'll wear many hats in this dynamic role.",
    requirements: "• 3+ years of HR generalist experience\n• Knowledge of HRIS systems and HR processes\n• Understanding of employment law and compliance\n• Experience with benefits administration\n• Strong communication and problem-solving skills\n• Bachelor's degree in HR or related field",
    responsibilities: "• Handle employee relations issues and investigations\n• Administer benefits programs and open enrollment\n• Support onboarding and offboarding processes\n• Maintain employee records and HR documentation\n• Assist with policy development and implementation",
    skills: ["HR Operations", "Employee Relations", "Benefits Administration", "HRIS"],
    benefits: "• Comprehensive benefits package\n• Health, dental, and vision insurance\n• 401(k) with company matching\n• Professional development support\n• Collaborative work environment"
  },
  {
    title: "Learning and Development Specialist",
    companyName: "SkillBuilder Corp",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 65000,
    maxSalary: 85000,
    description: "Design and deliver training programs that support employee growth and organizational development. You'll create engaging learning experiences and measure their impact.",
    requirements: "• 3+ years of learning and development experience\n• Experience with learning management systems (LMS)\n• Instructional design and curriculum development skills\n• Knowledge of adult learning principles\n• Presentation and facilitation skills\n• Bachelor's degree in Education, HR, or related field",
    responsibilities: "• Assess training needs and develop learning solutions\n• Create training materials and online courses\n• Facilitate workshops and training sessions\n• Manage learning management system\n• Evaluate training effectiveness and ROI",
    skills: ["Training Design", "LMS", "Instructional Design", "Facilitation"],
    benefits: "• Remote work flexibility\n• Professional development budget\n• Health insurance coverage\n• Learning and certification support\n• Career growth opportunities"
  },
  {
    title: "Compensation and Benefits Analyst",
    companyName: "RewardSystems Inc",
    location: "Dallas, TX",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 70000,
    maxSalary: 90000,
    description: "Analyze and design competitive compensation and benefits programs. You'll conduct market research and provide recommendations to ensure fair and competitive offerings.",
    requirements: "• 3+ years of compensation and benefits experience\n• Strong analytical and data analysis skills\n• Knowledge of compensation survey data and benchmarking\n• Experience with HRIS and compensation software\n• Understanding of benefits design and administration\n• Bachelor's degree in HR, Finance, or related field",
    responsibilities: "• Conduct compensation analysis and market studies\n• Design and implement compensation structures\n• Analyze benefits programs and make recommendations\n• Support annual compensation planning process\n• Ensure compliance with compensation regulations",
    skills: ["Compensation Analysis", "Benefits Design", "Data Analysis", "Market Research"],
    benefits: "• Competitive salary and annual bonus\n• Comprehensive benefits package\n• Flexible work arrangements\n• Professional certification support\n• Career advancement opportunities"
  },
  {
    title: "HR Operations Manager",
    companyName: "PeopleOps Solutions",
    location: "Seattle, WA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 90000,
    maxSalary: 120000,
    description: "Lead HR operations and ensure efficient delivery of HR services. You'll manage HR systems, processes, and policies while driving continuous improvement initiatives.",
    requirements: "• 5+ years of HR operations experience\n• Strong knowledge of HRIS systems and HR technology\n• Experience with process improvement and automation\n• Project management skills\n• Understanding of HR compliance and regulations\n• Bachelor's degree in HR or Business",
    responsibilities: "• Manage HR systems and technology implementations\n• Lead process improvement initiatives\n• Ensure HR compliance and audit readiness\n• Oversee HR metrics and reporting\n• Manage vendor relationships and contracts",
    skills: ["HR Operations", "HRIS", "Process Improvement", "Project Management"],
    benefits: "• Management-level compensation\n• Leadership development opportunities\n• Health and wellness benefits\n• Stock options\n• Professional development budget"
  },
  {
    title: "Diversity and Inclusion Specialist",
    companyName: "Inclusive Workplace Inc",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 70000,
    maxSalary: 95000,
    description: "Drive diversity, equity, and inclusion initiatives to create a more inclusive workplace. You'll develop programs and measure progress toward DEI goals.",
    requirements: "• 3+ years of DEI or related experience\n• Knowledge of diversity best practices and trends\n• Experience with DEI program development\n• Strong presentation and facilitation skills\n• Data analysis and reporting capabilities\n• Bachelor's degree in HR, Psychology, or related field",
    responsibilities: "• Develop and implement DEI strategies and programs\n• Conduct diversity training and workshops\n• Analyze workforce demographics and trends\n• Partner with leadership on inclusive hiring practices\n• Measure and report on DEI metrics and progress",
    skills: ["Diversity and Inclusion", "Program Development", "Training", "Data Analysis"],
    benefits: "• Mission-driven work\n• Remote work flexibility\n• Professional development support\n• Health insurance\n• DEI conference attendance"
  },
  {
    title: "Employee Relations Specialist",
    companyName: "WorkplaceHarmony HR",
    location: "Chicago, IL",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 65000,
    maxSalary: 85000,
    description: "Handle employee relations matters and ensure positive workplace relationships. You'll investigate complaints, mediate conflicts, and provide guidance on HR policies.",
    requirements: "• 3+ years of employee relations experience\n• Strong knowledge of employment law\n• Experience with workplace investigations\n• Excellent communication and conflict resolution skills\n• Understanding of HR policies and procedures\n• Bachelor's degree in HR or related field",
    responsibilities: "• Conduct workplace investigations and document findings\n• Mediate employee conflicts and disputes\n• Provide guidance on HR policies and procedures\n• Support managers with employee relations issues\n• Maintain confidential employee records",
    skills: ["Employee Relations", "Conflict Resolution", "Investigations", "Employment Law"],
    benefits: "• Specialized ER experience\n• Health and dental benefits\n• Professional development\n• Flexible work schedule\n• Legal training opportunities"
  },
  {
    title: "HR Information Systems Analyst",
    companyName: "HR Tech Solutions",
    location: "Austin, TX",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 75000,
    maxSalary: 100000,
    description: "Manage and optimize HR information systems to support HR operations. You'll work with HRIS platforms, data analysis, and system integrations.",
    requirements: "• 3+ years of HRIS or HR systems experience\n• Proficiency in HRIS platforms (Workday, SuccessFactors, BambooHR)\n• Strong analytical and problem-solving skills\n• Experience with data analysis and reporting\n• Knowledge of system integrations and APIs\n• Bachelor's degree in HR, IT, or related field",
    responsibilities: "• Maintain and configure HRIS systems\n• Develop reports and dashboards for HR metrics\n• Support system integrations and data flows\n• Troubleshoot system issues and provide user support\n• Participate in system upgrades and implementations",
    skills: ["HRIS", "Data Analysis", "System Administration", "Reporting"],
    benefits: "• Technical HR specialization\n• Competitive salary\n• Health benefits\n• Technology training\n• Career growth in HR tech"
  },
  {
    title: "Organizational Development Consultant",
    companyName: "OrgDev Partners",
    location: "San Francisco, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 95000,
    maxSalary: 130000,
    description: "Drive organizational effectiveness through change management and development initiatives. You'll work with leadership to design and implement transformation programs.",
    requirements: "• 5+ years of organizational development experience\n• Strong change management and consulting skills\n• Experience with organizational assessment and design\n• Knowledge of leadership development programs\n• Excellent facilitation and presentation abilities\n• Master's degree in OD, Psychology, or Business preferred",
    responsibilities: "• Assess organizational effectiveness and culture\n• Design and facilitate change management initiatives\n• Develop leadership and team development programs\n• Coach leaders on organizational challenges\n• Measure and evaluate program effectiveness",
    skills: ["Organizational Development", "Change Management", "Leadership Development", "Consulting"],
    benefits: "• Consulting opportunities\n• Leadership development exposure\n• Competitive compensation\n• Professional certification support\n• Travel opportunities"
  },

  // Other Professional Roles (15 jobs)
  {
    title: "Project Manager",
    companyName: "ProjectPro Solutions",
    location: "Atlanta, GA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 75000,
    maxSalary: 100000,
    description: "Lead cross-functional projects from initiation to completion. You'll coordinate resources, manage timelines, and ensure successful project delivery for our clients.",
    requirements: "• 4+ years of project management experience\n• PMP or similar certification preferred\n• Experience with project management tools (Jira, Asana, MS Project)\n• Strong organizational and communication skills\n• Agile and Scrum methodology experience\n• Bachelor's degree in Business or related field",
    responsibilities: "• Plan and execute projects from start to finish\n• Manage project scope, timeline, and budget\n• Coordinate cross-functional project teams\n• Communicate project status to stakeholders\n• Identify and mitigate project risks",
    skills: ["Project Management", "Agile", "Scrum", "Jira", "Risk Management"],
    benefits: "• Competitive salary and bonuses\n• Health and wellness benefits\n• Professional certification support\n• Flexible work schedule\n• Career development opportunities"
  },
  {
    title: "Data Analyst",
    companyName: "DataInsights Pro",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 70000,
    maxSalary: 95000,
    description: "Transform data into actionable insights that drive business decisions. You'll work with large datasets and create visualizations that tell compelling stories.",
    requirements: "• 3+ years of data analysis experience\n• Proficiency in SQL and data visualization tools (Tableau, Power BI)\n• Experience with Python or R for data analysis\n• Strong statistical analysis skills\n• Knowledge of database systems and data warehousing\n• Bachelor's degree in Statistics, Mathematics, or related field",
    responsibilities: "• Analyze complex datasets to identify trends and patterns\n• Create dashboards and reports for business stakeholders\n• Develop statistical models and predictive analytics\n• Collaborate with teams to understand data requirements\n• Present findings and recommendations to leadership",
    skills: ["Data Analysis", "SQL", "Python", "Tableau", "Statistics"],
    benefits: "• Fully remote position\n• Competitive salary\n• Health insurance coverage\n• Professional development budget\n• Flexible working hours"
  },
  {
    title: "UX/UI Designer",
    companyName: "DesignCraft Studio",
    location: "Portland, OR",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 80000,
    maxSalary: 110000,
    description: "Create intuitive and beautiful user experiences for web and mobile applications. You'll work closely with product teams to design solutions that delight users.",
    requirements: "• 3+ years of UX/UI design experience\n• Proficiency in design tools (Figma, Sketch, Adobe Creative Suite)\n• Experience with user research and usability testing\n• Understanding of responsive design principles\n• Knowledge of design systems and component libraries\n• Portfolio demonstrating design process and outcomes",
    responsibilities: "• Conduct user research and create user personas\n• Design wireframes, prototypes, and high-fidelity mockups\n• Collaborate with developers on design implementation\n• Conduct usability testing and iterate on designs\n• Maintain and evolve design systems",
    skills: ["UX Design", "UI Design", "Figma", "User Research", "Prototyping"],
    benefits: "• Creative work environment\n• Health and wellness benefits\n• Design conference attendance\n• Latest design tools and equipment\n• Professional growth opportunities"
  },
  {
    title: "Product Manager",
    companyName: "InnovateTech Products",
    location: "San Francisco, CA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 120000,
    maxSalary: 160000,
    description: "Drive product strategy and roadmap for our flagship software platform. You'll work with engineering, design, and business teams to deliver products that solve customer problems.",
    requirements: "• 5+ years of product management experience\n• Experience with agile development methodologies\n• Strong analytical and problem-solving skills\n• Knowledge of product management tools (Jira, Confluence, Roadmunk)\n• Technical background or ability to work closely with engineers\n• MBA or technical degree preferred",
    responsibilities: "• Define product vision and strategy\n• Develop and maintain product roadmap\n• Gather and prioritize product requirements\n• Work with engineering teams on product development\n• Analyze product metrics and user feedback",
    skills: ["Product Management", "Product Strategy", "Agile", "Analytics", "Roadmapping"],
    benefits: "• Competitive salary and equity\n• Comprehensive benefits package\n• Product conference attendance\n• Innovation time and resources\n• Career advancement opportunities"
  },
  {
    title: "Business Analyst",
    companyName: "BusinessSolutions Corp",
    location: "Washington, DC",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 70000,
    maxSalary: 95000,
    description: "Bridge the gap between business needs and technical solutions. You'll analyze business processes and requirements to help drive organizational improvements.",
    requirements: "• 3+ years of business analysis experience\n• Strong analytical and problem-solving skills\n• Experience with requirements gathering and documentation\n• Knowledge of business process modeling\n• Proficiency in analysis tools (Excel, Visio, SQL)\n• Bachelor's degree in Business or related field",
    responsibilities: "• Gather and document business requirements\n• Analyze business processes and identify improvements\n• Create functional specifications and user stories\n• Facilitate stakeholder meetings and workshops\n• Support testing and implementation of solutions",
    skills: ["Business Analysis", "Requirements Gathering", "Process Improvement", "SQL"],
    benefits: "• Competitive salary\n• Health and dental insurance\n• Professional development opportunities\n• Flexible work arrangements\n• Career growth potential"
  },
  {
    title: "Financial Analyst",
    companyName: "FinanceMax Solutions",
    location: "New York, NY",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 70000,
    maxSalary: 95000,
    description: "Provide financial analysis and insights to support business decision-making. You'll work on budgeting, forecasting, and financial modeling for various business units.",
    requirements: "• 3+ years of financial analysis experience\n• Strong proficiency in Excel and financial modeling\n• Knowledge of accounting principles and financial statements\n• Experience with financial planning software\n• CPA or CFA certification preferred\n• Bachelor's degree in Finance or Accounting",
    responsibilities: "• Prepare financial reports and variance analysis\n• Support budgeting and forecasting processes\n• Create financial models for business initiatives\n• Analyze financial performance and trends\n• Present findings to senior management",
    skills: ["Financial Analysis", "Excel", "Financial Modeling", "Budgeting", "Forecasting"],
    benefits: "• Competitive salary and bonuses\n• Comprehensive benefits package\n• Professional certification support\n• Career advancement opportunities\n• Finance training programs"
  },
  {
    title: "Operations Manager",
    companyName: "EfficiencyPro Operations",
    location: "Chicago, IL",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 85000,
    maxSalary: 115000,
    description: "Oversee daily operations and implement process improvements to drive efficiency. You'll manage teams and ensure smooth execution of business operations.",
    requirements: "• 5+ years of operations management experience\n• Strong leadership and team management skills\n• Experience with process improvement methodologies (Lean, Six Sigma)\n• Knowledge of project management principles\n• Data analysis and reporting skills\n• Bachelor's degree in Operations or Business",
    responsibilities: "• Manage daily operations and team performance\n• Identify and implement process improvements\n• Develop operational policies and procedures\n• Monitor KPIs and operational metrics\n• Collaborate with other departments on cross-functional initiatives",
    skills: ["Operations Management", "Process Improvement", "Team Leadership", "Lean Six Sigma"],
    benefits: "• Management-level compensation\n• Health and wellness benefits\n• Leadership development programs\n• Performance bonuses\n• Career advancement opportunities"
  },
  {
    title: "Technical Support Specialist",
    companyName: "TechSupport Pro",
    location: "Austin, TX",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "entry",
    minSalary: 45000,
    maxSalary: 60000,
    description: "Provide technical support to customers and resolve complex technical issues. You'll troubleshoot problems and ensure excellent customer experiences.",
    requirements: "• 1-3 years of technical support experience\n• Strong troubleshooting and problem-solving skills\n• Knowledge of software applications and operating systems\n• Excellent customer service and communication skills\n• Experience with ticketing systems\n• Technical certifications preferred",
    responsibilities: "• Respond to customer support tickets and phone calls\n• Troubleshoot technical issues and provide solutions\n• Escalate complex problems to senior team members\n• Document solutions and maintain knowledge base\n• Provide product training to customers",
    skills: ["Technical Support", "Troubleshooting", "Customer Service", "Ticketing Systems"],
    benefits: "• Competitive starting salary\n• Health and dental insurance\n• Technical training opportunities\n• Career advancement path\n• Supportive team environment"
  },
  {
    title: "Content Writer",
    companyName: "WordCraft Content",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 50000,
    maxSalary: 70000,
    description: "Create engaging content across various formats and channels. You'll write blog posts, articles, marketing copy, and other content that drives engagement and conversions.",
    requirements: "• 3+ years of professional writing experience\n• Excellent writing, editing, and proofreading skills\n• Experience with content management systems\n• Knowledge of SEO writing best practices\n• Ability to write for different audiences and formats\n• Bachelor's degree in English, Journalism, or related field",
    responsibilities: "• Write blog posts, articles, and web content\n• Create marketing copy for various campaigns\n• Collaborate with marketing and design teams\n• Optimize content for search engines\n• Maintain brand voice and messaging consistency",
    skills: ["Content Writing", "SEO Writing", "Copywriting", "Editing"],
    benefits: "• Fully remote work\n• Creative freedom\n• Health insurance\n• Professional development\n• Writing portfolio building"
  },
  {
    title: "Supply Chain Analyst",
    companyName: "LogisticsPro Solutions",
    location: "Dallas, TX",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 65000,
    maxSalary: 85000,
    description: "Optimize supply chain operations through data analysis and process improvement. You'll work with vendors, logistics, and inventory management systems.",
    requirements: "• 3+ years of supply chain or logistics experience\n• Strong analytical and problem-solving skills\n• Experience with supply chain software and ERP systems\n• Knowledge of inventory management and forecasting\n• Understanding of logistics and transportation\n• Bachelor's degree in Supply Chain, Business, or related field",
    responsibilities: "• Analyze supply chain performance and identify improvements\n• Manage vendor relationships and contracts\n• Optimize inventory levels and forecasting\n• Coordinate with logistics and operations teams\n• Develop reports and dashboards for supply chain metrics",
    skills: ["Supply Chain Management", "Data Analysis", "Inventory Management", "ERP Systems"],
    benefits: "• Supply chain specialization\n• Health and dental benefits\n• Professional development\n• Industry conference attendance\n• Career growth opportunities"
  },
  {
    title: "Quality Assurance Manager",
    companyName: "QualityFirst Manufacturing",
    location: "Phoenix, AZ",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 80000,
    maxSalary: 105000,
    description: "Lead quality assurance programs and ensure products meet quality standards. You'll manage QA teams and implement quality management systems.",
    requirements: "• 5+ years of quality assurance experience\n• Experience with quality management systems (ISO 9001)\n• Strong knowledge of QA methodologies and tools\n• Team leadership and management experience\n• Understanding of statistical process control\n• Bachelor's degree in Engineering or related field",
    responsibilities: "• Develop and implement quality assurance programs\n• Lead QA team and provide training and guidance\n• Conduct quality audits and inspections\n• Investigate quality issues and implement corrective actions\n• Maintain quality documentation and records",
    skills: ["Quality Assurance", "Team Management", "ISO 9001", "Statistical Process Control"],
    benefits: "• Management-level position\n• Quality specialization\n• Health benefits\n• Professional certification support\n• Career advancement"
  },
  {
    title: "Research Analyst",
    companyName: "MarketResearch Insights",
    location: "Boston, MA",
    workMode: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 60000,
    maxSalary: 80000,
    description: "Conduct market research and analysis to support business strategy. You'll gather data, analyze trends, and provide insights that inform decision-making.",
    requirements: "• 3+ years of research or analysis experience\n• Strong analytical and critical thinking skills\n• Experience with research methodologies and tools\n• Proficiency in data analysis software (SPSS, R, Excel)\n• Excellent written and verbal communication\n• Bachelor's degree in Business, Economics, or related field",
    responsibilities: "• Design and conduct market research studies\n• Analyze data and identify trends and patterns\n• Prepare research reports and presentations\n• Monitor industry trends and competitive landscape\n• Support strategic planning and business development",
    skills: ["Market Research", "Data Analysis", "Statistical Analysis", "Report Writing"],
    benefits: "• Research specialization\n• Health insurance\n• Professional development\n• Conference attendance\n• Analytical skill building"
  },
  {
    title: "Event Coordinator",
    companyName: "EventPro Management",
    location: "Las Vegas, NV",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 45000,
    maxSalary: 65000,
    description: "Plan and execute corporate events, conferences, and meetings. You'll coordinate all aspects of event planning from venue selection to post-event follow-up.",
    requirements: "• 3+ years of event planning experience\n• Strong organizational and project management skills\n• Experience with event management software\n• Excellent vendor management and negotiation abilities\n• Attention to detail and ability to multitask\n• Bachelor's degree in Hospitality, Marketing, or related field",
    responsibilities: "• Plan and coordinate corporate events and meetings\n• Manage event budgets and vendor relationships\n• Coordinate logistics including venues, catering, and equipment\n• Oversee event setup and execution\n• Conduct post-event analysis and reporting",
    skills: ["Event Planning", "Project Management", "Vendor Management", "Budget Management"],
    benefits: "• Event industry exposure\n• Travel opportunities\n• Health benefits\n• Creative work environment\n• Industry networking"
  },
  {
    title: "Training Specialist",
    companyName: "SkillDevelopment Corp",
    location: "Remote",
    workMode: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 55000,
    maxSalary: 75000,
    description: "Develop and deliver training programs for corporate clients. You'll create curriculum, facilitate workshops, and measure training effectiveness.",
    requirements: "• 3+ years of training and development experience\n• Experience with instructional design and curriculum development\n• Strong presentation and facilitation skills\n• Knowledge of learning management systems\n• Understanding of adult learning principles\n• Bachelor's degree in Education or related field",
    responsibilities: "• Design and develop training curricula and materials\n• Facilitate training sessions and workshops\n• Assess training needs and learning objectives\n• Evaluate training effectiveness and gather feedback\n• Maintain training records and documentation",
    skills: ["Training Development", "Instructional Design", "Facilitation", "Curriculum Design"],
    benefits: "• Remote work flexibility\n• Training industry exposure\n• Professional development\n• Health insurance\n• Skills development"
  },
  {
    title: "Administrative Manager",
    companyName: "BusinessSupport Services",
    location: "Minneapolis, MN",
    workMode: "onsite",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 50000,
    maxSalary: 70000,
    description: "Oversee administrative operations and support business functions. You'll manage office operations, coordinate administrative staff, and ensure efficient workflows.",
    requirements: "• 4+ years of administrative or office management experience\n• Strong organizational and leadership skills\n• Experience with office management software and systems\n• Knowledge of business operations and processes\n• Excellent communication and interpersonal skills\n• Bachelor's degree in Business Administration or related field",
    responsibilities: "• Manage daily office operations and administrative functions\n• Supervise and coordinate administrative staff\n• Develop and implement administrative policies and procedures\n• Coordinate meetings, travel, and special projects\n• Manage office budgets and vendor relationships",
    skills: ["Office Management", "Team Leadership", "Administrative Operations", "Process Management"],
    benefits: "• Management experience\n• Comprehensive benefits\n• Professional development\n• Stable work environment\n• Career advancement"
  }
];

async function loginAndCreateJobs() {
  console.log('Logging in as recruiter...');
  
  // Login first
  const loginResponse = await fetch('http://localhost:5000/api/auth/email/login', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      email: 'shubhamdubexskd2001@gmail.com',
      password: '12345678'
    })
  });
  
  if (!loginResponse.ok) {
    console.error('Login failed:', await loginResponse.text());
    return;
  }
  
  // Extract session cookie
  const cookies = loginResponse.headers.get('set-cookie');
  console.log(`Login successful, creating ${jobs.length} jobs...`);
  
  // Create jobs one by one
  for (let i = 0; i < jobs.length; i++) {
    const job = jobs[i];
    try {
      const response = await fetch('http://localhost:5000/api/recruiter/jobs', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Cookie': cookies || ''
        },
        body: JSON.stringify(job)
      });
      
      if (response.ok) {
        console.log(`✅ [${i + 1}/${jobs.length}] Created: ${job.title} at ${job.companyName}`);
      } else {
        const error = await response.text();
        console.log(`❌ [${i + 1}/${jobs.length}] Failed: ${job.title} - ${error}`);
      }
    } catch (error) {
      console.log(`❌ [${i + 1}/${jobs.length}] Error: ${job.title} - ${error.message}`);
    }
    
    // Small delay to avoid overwhelming the server
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  
  console.log(`\n🎉 Job creation process completed! Successfully created jobs across all categories.`);
  console.log(`📊 Total jobs created: ${jobs.length}`);
  console.log(`📋 Categories: Software Engineering (15), Marketing (10), Sales (10), HR (10), Other Professional Roles (15)`);
}

loginAndCreateJobs().catch(console.error);