[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26.3",
    "pandas>=2.3.1",
    "psycopg2-binary>=2.9.10",
    "python-jobspy>=1.1.82",
    "requests>=2.32.5",
    "tsx>=0.2.11",
]
