[deployment]
run = ["sh", "-c", "npm run build && npm run start"]

[interpreter]
command = ["tsx", "server/index.ts"]

[interpreter.env]
NODE_ENV = "development"

[[ports]]
localPort = 5000
externalPort = 80